spring.application.name=SpringSecEx
spring.security.user.name=aryan
spring.security.user.password=disha

spring.datasource.url=jdbc:mysql://localhost:3306/springproject
spring.datasource.username=root
spring.datasource.password=ADMIN123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

